### ISSUE TITLE
Best time line

### ISSUE THREAD

**Issue by Combinacijusx** [aricneto/TwistyTimer#37]
Graph could also display line of best time. Not straight line of current best time but line for every record until it's beaten.

**Comment by damo** [comment]
I have (mostly) implemented a chart line for the progression of the best time. Still a few things to fix, but it can be previewed at https://github.com/damo/TwistyTimer/tree/session_stats

Here are some screen shots of its current state.

For the current session, the Ao5 and Ao12 lines are shown. The "best" times graphed are those since the start of the session.

![screenshot_20160817-153641](https://cloud.githubusercontent.com/assets/145233/17740513/c7dfd320-6490-11e6-8422-938ce51eb39b.png)

Here is the chart of the full history of all times. The Ao50 and Ao100 lines are shown. The "best" values are shown on the chart unless there are too many points present (as below).

![screenshot_20160817-153714](https://cloud.githubusercontent.com/assets/145233/17740515/c7e9ab0c-6490-11e6-963b-fe55b964c3c5.png)

If there are lots of points, zoom in and the values will appear (as below).

![screenshot_20160817-153727](https://cloud.githubusercontent.com/assets/145233/17740514/c7e090bc-6490-11e6-81da-7610c55b48a3.png)

**Comment by Combinacijusx** [comment]
You could also add feature to toggle lines by pressing on that text

![capture](https://cloud.githubusercontent.com/assets/16375702/17741358/8ae59d92-64a4-11e6-870c-145517fb5413.PNG)
